name: VM3 PM Release Gate 261011A
on:
  pull_request:
    branches:
      - vm3-pmrel-treatment-261011a
permissions:
  contents: read
jobs:
  vm3-pmrelease-gate:
    runs-on: ubuntu-latest
    steps:
      - run: echo VM3_PM_RELEASE_GATE_SUCCESS_261011A
